// vue-frontend/src/components/Menu.vue
<template>
  <div class="row">
      <nav class="col-md-2 d-none d-md-block bg-light sidebar">
        <div class="sidebar-sticky">
          <ul class="nav flex-column">
            <li class="nav-item">
              <a class="nav-link active" href="#"> Products </a>
            </li>
          </ul>
        </div>
      </nav>
</template>

<script>
export default {
  name: "Menu",
};
</script>

<style scoped></style>

// react-frontend/src/components/Menu.tsx
import React from "react";

const Menu = () => {
  return (
    <nav className="col-md-2 d-none d-md-block bg-light sidebar">
      <div className="sidebar-sticky">
        <ul className="nav flex-column">
          <li className="nav-item">
            <a className="nav-link active" href="#">
              Products
            </a>
          </li>
        </ul>
      </div>
    </nav>
  );
};

export default Menu;
